# Import data

In [ ]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('climate-change.csv')
df.head()

,Country Name,Country Code,Year,average_value_Access to electricity (% of population),average_value_Agricultural land (% of land area),average_value_Agricultural land (sq. km),"average_value_Agriculture, forestry, and fishing, value added (% of GDP)","average_value_Annual freshwater withdrawals, total (% of internal resources)","average_value_Annual freshwater withdrawals, total (billion cubic meters)",average_value_Arable land (% of land area),...,"average_value_School enrollment, primary and secondary (gross), gender parity index (GPI)",average_value_Terrestrial and marine protected areas (% of total territorial area),average_value_Terrestrial protected areas (% of total land area),average_value_Total greenhouse gas emissions (kt of CO2 equivalent),average_value_Urban land area where elevation is below 5 meters (% of total land area),average_value_Urban land area where elevation is below 5 meters (sq. km),average_value_Urban population,average_value_Urban population (% of total population),average_value_Urban population growth (annual %),average_value_Urban population living in areas where elevation is below 5 meters (% of total population)
0,Africa Eastern and Southern,AFE,1987,NaN,44.513309,5428670.0,15.468203,NaN,NaN,5.748789,...,NaN,NaN,NaN,1.928434e+06,NaN,NaN,65511328.0,23.465243,5.030075,NaN
1,Albania,ALB,1977,NaN,40.474453,11090.0,NaN,NaN,NaN,21.167883,...,NaN,NaN,NaN,8.948981e+03,NaN,NaN,832109.0,33.105000,2.810025,NaN
2,Albania,ALB,2019,100.0,NaN,NaN,18.463380,NaN,NaN,NaN,...,1.01863,NaN,NaN,NaN,NaN,NaN,1747593.0,61.229000,1.071414,NaN
3,Armenia,ARM,2020,NaN,NaN,NaN,11.717313,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1876112.0,63.313000,0.334548,NaN
4,Azerbaijan,AZE,2013,100.0,57.704545,47698.0,5.366264,NaN,NaN,23.292080,...,NaN,NaN,NaN,8.303000e+04,NaN,NaN,5098727.0,54.145000,1.778515,NaN

# Brief EDA 
## columns

In [4]:
df.columns

Index(['Country Name', 'Country Code', 'Year',
       'average_value_Access to electricity (% of population)',
       'average_value_Agricultural land (% of land area)',
       'average_value_Agricultural land (sq. km)',
       'average_value_Agriculture, forestry, and fishing, value added (% of GDP)',
       'average_value_Annual freshwater withdrawals, total (% of internal resources)',
       'average_value_Annual freshwater withdrawals, total (billion cubic meters)',
       'average_value_Arable land (% of land area)',
       'average_value_CO2 emissions (kg per 2010 US$ of GDP)',
       'average_value_CO2 emissions (kg per 2017 PPP $ of GDP)',
       'average_value_CO2 emissions (kt)',
       'average_value_CO2 emissions (metric tons per capita)',
       'average_value_CO2 emissions from gaseous fuel consumption (% of total)',
       'average_value_CO2 emissions from gaseous fuel consumption (kt)',
       'average_value_CO2 emissions from liquid fuel consumption (% of total)',
       'average_value_CO2 emissions from liquid fuel consumption (kt)',
       'average_value_CO2 emissions from solid fuel consumption (% of total)',
       'average_value_CO2 emissions from solid fuel consumption (kt)',
       'average_value_CPIA public sector management and institutions cluster average (1=low to 6=high)',
       'average_value_Foreign direct investment, net inflows (% of GDP)',
       'average_value_Forest area (% of land area)',
       'average_value_Forest area (sq. km)',
       'average_value_Land area where elevation is below 5 meters (% of total land area)',
       'average_value_Marine protected areas (% of territorial waters)',
       'average_value_Methane emissions (% change from 1990)',
       'average_value_Methane emissions (kt of CO2 equivalent)',
       'average_value_Mortality rate, under-5 (per 1,000 live births)',
       'average_value_Nitrous oxide emissions (% change from 1990)',
       'average_value_Nitrous oxide emissions (thousand metric tons of CO2 equivalent)',
       'average_value_Other greenhouse gas emissions (% change from 1990)',
       'average_value_Other greenhouse gas emissions, HFC, PFC and SF6 (thousand metric tons of CO2 equivalent)',
       'average_value_Population growth (annual %)',
       'average_value_Population in urban agglomerations of more than 1 million (% of total population)',
       'average_value_Population living in areas where elevation is below 5 meters (% of total population)',
       'average_value_Population, total',
       'average_value_Primary completion rate, total (% of relevant age group)',
       'average_value_Renewable electricity output (% of total electricity output)',
       'average_value_Renewable energy consumption (% of total final energy consumption)',
       'average_value_Rural land area where elevation is below 5 meters (% of total land area)',
       'average_value_Rural land area where elevation is below 5 meters (sq. km)',
       'average_value_Rural population living in areas where elevation is below 5 meters (% of total population)',
       'average_value_School enrollment, primary and secondary (gross), gender parity index (GPI)',
       'average_value_Terrestrial and marine protected areas (% of total territorial area)',
       'average_value_Terrestrial protected areas (% of total land area)',
       'average_value_Total greenhouse gas emissions (kt of CO2 equivalent)',
       'average_value_Urban land area where elevation is below 5 meters (% of total land area)',
       'average_value_Urban land area where elevation is below 5 meters (sq. km)',
       'average_value_Urban population',
       'average_value_Urban population (% of total population)',
       'average_value_Urban population growth (annual %)',
       'average_value_Urban population living in areas where elevation is below 5 meters (% of total population)'],
      dtype='str')

In [ ]:
# focusing on data columns related to co2 emissions and population
id_cols = ['Country Name', 'Country Code', 'Year']
co2_pop_cols = df.columns[df.columns.str.contains('CO2|Population')].to_list()
df2 = df[id_cols+co2_pop_cols]
df2.dropna(inplace=True, how='all')
df2

,Country Name,Country Code,Year,average_value_CO2 emissions (kg per 2010 US$ of GDP),average_value_CO2 emissions (kg per 2017 PPP $ of GDP),average_value_CO2 emissions (kt),average_value_CO2 emissions (metric tons per capita),average_value_CO2 emissions from gaseous fuel consumption (% of total),average_value_CO2 emissions from gaseous fuel consumption (kt),average_value_CO2 emissions from liquid fuel consumption (% of total),...,average_value_CO2 emissions from solid fuel consumption (% of total),average_value_CO2 emissions from solid fuel consumption (kt),average_value_Methane emissions (kt of CO2 equivalent),average_value_Nitrous oxide emissions (thousand metric tons of CO2 equivalent),"average_value_Other greenhouse gas emissions, HFC, PFC and SF6 (thousand metric tons of CO2 equivalent)",average_value_Population growth (annual %),average_value_Population in urban agglomerations of more than 1 million (% of total population),average_value_Population living in areas where elevation is below 5 meters (% of total population),"average_value_Population, total",average_value_Total greenhouse gas emissions (kt of CO2 equivalent)
0,Africa Eastern and Southern,AFE,1987,0.993841,NaN,388106.047579,1.390142,0.078477,NaN,18.177590,...,79.640556,444287.261378,376226.647,267243.990962,1.294200e+06,3.001095,10.042830,NaN,279184536.0,1.928434e+06
1,Albania,ALB,1977,NaN,NaN,5720.520000,2.275876,12.243590,700.397,51.538462,...,29.743590,1701.488000,2002.100,1007.155900,2.373130e+02,2.213252,NaN,NaN,2513546.0,8.948981e+03
2,Albania,ALB,2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-0.426007,NaN,NaN,2854191.0,NaN
3,Armenia,ARM,2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.185983,36.658428,NaN,2963234.0,NaN
4,Azerbaijan,AZE,2013,0.557209,0.227494,31390.000000,3.333404,63.503702,19933.812,37.978391,...,0.035046,11.001000,47740.000,3520.000000,1.679155e+03,1.293447,22.883525,NaN,9416801.0,8.303000e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16160,Uzbekistan,UZB,1978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,23358.300,9204.706000,-2.490363e+04,2.783544,11.637980,NaN,15057226.0,7.904405e+04
16161,Vanuatu,VUT,1976,NaN,NaN,44.004000,0.427215,0.000000,0.000,100.000000,...,0.000000,0.000000,179.577,77.233710,2.032571e+01,3.094916,NaN,NaN,103002.0,3.070140e+02
16162,"Yemen, Rep.",YEM,1963,NaN,NaN,80.674000,0.014518,0.000000,0.000,100.000000,...,0.000000,0.000000,NaN,NaN,NaN,1.506696,1.473537,NaN,5556767.0,NaN
16163,South Africa,ZAF,1969,1.094303,NaN,143280.691000,6.665435,0.000000,0.000,13.907302,...,84.316536,120809.315000,NaN,NaN,NaN,2.610663,24.215351,NaN,21496075.0,NaN
16164,Zimbabwe,ZWE,2008,0.846108,0.326411,7600.000000,0.613916,0.000000,0.000,21.181750,...,78.454500,5962.542000,10430.000,5840.000000,-3.049231e+01,1.003707,11.830888,NaN,12379553.0,2.415000e+04

In [7]:
np.sort(df2['Year'].unique())

array([1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970,
       1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981,
       1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992,
       1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019, 2020], dtype=int64)

In [ ]:
# filtering for year=2018
df2.groupby('Year').count().sort_values('average_value_CO2 emissions (kt)', ascending=False).loc[2018]

Country Name                                                                                               265
Country Code                                                                                               265
average_value_CO2 emissions (kg per 2010 US$ of GDP)                                                       231
average_value_CO2 emissions (kg per 2017 PPP $ of GDP)                                                     228
average_value_CO2 emissions (kt)                                                                           239
average_value_CO2 emissions (metric tons per capita)                                                       239
average_value_CO2 emissions from gaseous fuel consumption (% of total)                                       0
average_value_CO2 emissions from gaseous fuel consumption (kt)                                               0
average_value_CO2 emissions from liquid fuel consumption (% of total)                                        0
average_value_CO2 emissions from liquid fuel consumption (kt)                                                0
average_value_CO2 emissions from solid fuel consumption (% of total)                                         0
average_value_CO2 emissions from solid fuel consumption (kt)                                                 0
average_value_Methane emissions (kt of CO2 equivalent)                                                     239
average_value_Nitrous oxide emissions (thousand metric tons of CO2 equivalent)                             239
average_value_Other greenhouse gas emissions, HFC, PFC and SF6 (thousand metric tons of CO2 equivalent)      0
average_value_Population growth (annual %)                                                                 264
average_value_Population in urban agglomerations of more than 1 million (% of total population)            159
average_value_Population living in areas where elevation is below 5 meters (% of total population)           0
average_value_Population, total                                                                            264
average_value_Total greenhouse gas emissions (kt of CO2 equivalent)                                        239
Name: 2018, dtype: int64

## country names
There are odd "country names" that are actually regions, continents, or transformed attributes.

Found another dataset from [this GitHub repo](https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes) which has all country regional codes that match with our data. Use this to merge and filter our data Country Code.

In [23]:
iso = pd.read_csv('country_ISOcode.csv')
iso = iso[['name', 'alpha-3']]
iso

                  name alpha-3
0          Afghanistan     AFG
1        Åland Islands     ALA
2              Albania     ALB
3              Algeria     DZA
4       American Samoa     ASM
..                 ...     ...
244  Wallis and Futuna     WLF
245     Western Sahara     ESH
246              Yemen     YEM
247             Zambia     ZMB
248           Zimbabwe     ZWE

[249 rows x 2 columns]

In [34]:
df2_2018 = df2[df2['Year']==2018]
df2_2018 = df2_2018.merge(iso, how='inner', left_on='Country Code', right_on='alpha-3')
df2_2018.drop(axis=1, labels=['name', 'alpha-3'], inplace=True)
df2_2018.dropna(axis=0, inplace=True, subset='average_value_CO2 emissions (kt)')
df2_2018

,Country Name,Country Code,Year,average_value_CO2 emissions (kg per 2010 US$ of GDP),average_value_CO2 emissions (kg per 2017 PPP $ of GDP),average_value_CO2 emissions (kt),average_value_CO2 emissions (metric tons per capita),average_value_CO2 emissions from gaseous fuel consumption (% of total),average_value_CO2 emissions from gaseous fuel consumption (kt),average_value_CO2 emissions from liquid fuel consumption (% of total),...,average_value_CO2 emissions from solid fuel consumption (% of total),average_value_CO2 emissions from solid fuel consumption (kt),average_value_Methane emissions (kt of CO2 equivalent),average_value_Nitrous oxide emissions (thousand metric tons of CO2 equivalent),"average_value_Other greenhouse gas emissions, HFC, PFC and SF6 (thousand metric tons of CO2 equivalent)",average_value_Population growth (annual %),average_value_Population in urban agglomerations of more than 1 million (% of total population),average_value_Population living in areas where elevation is below 5 meters (% of total population),"average_value_Population, total",average_value_Total greenhouse gas emissions (kt of CO2 equivalent)
0,Trinidad and Tobago,TTO,2018,0.842645,0.486791,17760.0,12.778440,NaN,NaN,NaN,...,NaN,NaN,1280.0,390.0,NaN,0.416814,NaN,NaN,1389841.0,22900.0
1,South Africa,ZAF,2018,1.008704,0.593656,433250.0,7.496645,NaN,NaN,NaN,...,NaN,NaN,45140.0,18820.0,NaN,1.363703,35.299944,NaN,57792520.0,513440.0
2,Bosnia and Herzegovina,BIH,2018,1.112223,0.471346,22540.0,6.781132,NaN,NaN,NaN,...,NaN,NaN,3380.0,1090.0,NaN,-0.827063,NaN,NaN,3323929.0,27190.0
3,Liechtenstein,LIE,2018,NaN,NaN,140.0,3.692178,NaN,NaN,NaN,...,NaN,NaN,20.0,10.0,NaN,0.298456,NaN,NaN,37918.0,180.0
4,Oman,OMN,2018,0.969769,0.535860,73370.0,15.192124,NaN,NaN,NaN,...,NaN,NaN,5460.0,780.0,NaN,3.445166,29.952794,NaN,4829476.0,82300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,Paraguay,PRY,2018,0.225453,0.094362,8420.0,1.210454,NaN,NaN,NaN,...,NaN,NaN,29070.0,10070.0,NaN,1.287874,46.322125,NaN,6956069.0,49170.0
210,Suriname,SUR,2018,0.433605,0.190006,2080.0,3.611193,NaN,NaN,NaN,...,NaN,NaN,1370.0,240.0,NaN,0.957017,NaN,NaN,575987.0,3780.0
212,Canada,CAN,2018,0.299550,0.317583,574400.0,15.497025,NaN,NaN,NaN,...,NaN,NaN,93980.0,43120.0,NaN,1.412548,45.924692,NaN,37065178.0,724930.0
213,Kiribati,KIR,2018,0.388457,0.306379,80.0,0.690596,NaN,NaN,NaN,...,NaN,NaN,20.0,10.0,NaN,1.468754,NaN,NaN,115842.0,110.0
214,"Korea, Rep.",KOR,2018,0.434147,0.291420,630870.0,12.224591,NaN,NaN,NaN,...,NaN,NaN,25530.0,10770.0,NaN,0.475334,50.173971,NaN,51606633.0,718880.0

## describe the data
Some quick statistics and sorting.

Filtered 2018 dataset is exported as CSV and used to make visualizations in Tableau.

In [35]:
df2_2018['average_value_CO2 emissions (kt)'].describe()

count    1.910000e+02
mean     1.758063e+05
std      8.565224e+05
min      1.000000e+01
25%      2.275000e+03
50%      1.159000e+04
75%      6.598500e+04
max      1.031346e+07
Name: average_value_CO2 emissions (kt), dtype: float64

In [38]:
df2_2018.sort_values('average_value_CO2 emissions (kt)', ascending=False)[:10]

,Country Name,Country Code,Year,average_value_CO2 emissions (kg per 2010 US$ of GDP),average_value_CO2 emissions (kg per 2017 PPP $ of GDP),average_value_CO2 emissions (kt),average_value_CO2 emissions (metric tons per capita),average_value_CO2 emissions from gaseous fuel consumption (% of total),average_value_CO2 emissions from gaseous fuel consumption (kt),average_value_CO2 emissions from liquid fuel consumption (% of total),...,average_value_CO2 emissions from solid fuel consumption (% of total),average_value_CO2 emissions from solid fuel consumption (kt),average_value_Methane emissions (kt of CO2 equivalent),average_value_Nitrous oxide emissions (thousand metric tons of CO2 equivalent),"average_value_Other greenhouse gas emissions, HFC, PFC and SF6 (thousand metric tons of CO2 equivalent)",average_value_Population growth (annual %),average_value_Population in urban agglomerations of more than 1 million (% of total population),average_value_Population living in areas where elevation is below 5 meters (% of total population),"average_value_Population, total",average_value_Total greenhouse gas emissions (kt of CO2 equivalent)
70,China,CHN,2018,0.948528,0.485811,10313460.0,7.405211,NaN,NaN,NaN,...,NaN,NaN,1238630.0,538790.0,NaN,0.455900,27.887562,NaN,1.392730e+09,12355240.0
162,United States,USA,2018,0.277341,0.247474,4981300.0,15.240875,NaN,NaN,NaN,...,NaN,NaN,622590.0,250060.0,NaN,0.526435,46.304526,NaN,3.268382e+08,6023620.0
129,India,IND,2018,0.861293,0.276096,2434520.0,1.799825,NaN,NaN,NaN,...,NaN,NaN,666510.0,253790.0,NaN,1.037828,15.434796,NaN,1.352642e+09,3374990.0
175,Russian Federation,RUS,2018,0.921908,0.410720,1607550.0,11.126618,NaN,NaN,NaN,...,NaN,NaN,849570.0,58610.0,NaN,-0.013067,23.191361,NaN,1.444779e+08,2543400.0
25,Japan,JPN,2018,0.179269,0.212282,1106150.0,8.742258,NaN,NaN,NaN,...,NaN,NaN,21110.0,18010.0,NaN,-0.202670,64.628042,NaN,1.265291e+08,1186770.0
140,Germany,DEU,2018,0.180886,0.160079,709540.0,8.558390,NaN,NaN,NaN,...,NaN,NaN,53370.0,32900.0,NaN,0.300527,9.583031,NaN,8.290578e+07,806090.0
214,"Korea, Rep.",KOR,2018,0.434147,0.291420,630870.0,12.224591,NaN,NaN,NaN,...,NaN,NaN,25530.0,10770.0,NaN,0.475334,50.173971,NaN,5.160663e+07,718880.0
159,"Iran, Islamic Rep.",IRN,2018,1.194554,0.571043,629290.0,7.693013,NaN,NaN,NaN,...,NaN,NaN,149690.0,37580.0,NaN,1.386478,25.988742,NaN,8.180020e+07,828280.0
123,Indonesia,IDN,2018,0.508421,0.191568,583110.0,2.178462,NaN,NaN,NaN,...,NaN,NaN,287500.0,95690.0,NaN,1.134507,13.383052,NaN,2.676705e+08,969580.0
212,Canada,CAN,2018,0.299550,0.317583,574400.0,15.497025,NaN,NaN,NaN,...,NaN,NaN,93980.0,43120.0,NaN,1.412548,45.924692,NaN,3.706518e+07,724930.0

In [37]:
df2_2018['average_value_CO2 emissions (kt)'].quantile(0.9)

309960.0

In [20]:
df2_2018['Country Name'].unique()

<ArrowStringArray>
[       'Trinidad and Tobago',               'South Africa',
     'Bosnia and Herzegovina',              'Liechtenstein',
                       'Oman',         'Dominican Republic',
                  'Euro area',                      'Malta',
             'American Samoa',                     'France',
 ...
                     'Turkey',                   'Eswatini',
                  'Guatemala',                   'Paraguay',
 'Africa Western and Central',                   'Suriname',
                       'Guam',                     'Canada',
                   'Kiribati',                'Korea, Rep.']
Length: 265, dtype: str

In [36]:
df2_2018.to_csv('2018.csv')